project:
  type: website
  output-dir: docs

website:
  title: "Thomas Fox"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "CV"
        href:  ThomasFox_Resume.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



